language: java
cache:
  directories:
  - ".gradle"
script:
- "./gradlew build test publish --stacktrace"
deploy:
  provider: releases
  api_key:
    secure: o4uBFbenIC2Yd/RIaf4oASGa671zQMr0aL6UT76RBsLzg+/BKONg2A9KXg1BY/59CqCvrsMtT0qh4yhdDtuC6qZSUjPBvntqwCzV6WOPQQVgLqpk87tZtusSuqabxGo0dsQEDeU70Z3CE+rRpd+QmEE6aegPm6Vj5Htwu7hMGPE=
  file: build/artifacts/*
  file_glob: true
  on:
    tags: true
